"""changed the password length

Revision ID: ef3a85979d21
Revises: b6c8b901d4d1
Create Date: 2025-02-08 00:11:56.686205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef3a85979d21'
down_revision = 'b6c8b901d4d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done_by', sa.DateTime(), nullable=False))
        batch_op.drop_column('Done_by')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Done_by', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('done_by')

    # ### end Alembic commands ###
